#!/usr/bin/env python3
"""Titres des actualités et des enseignements en anglais et en arabe (par nom de page).
Les articles eux-mêmes restent en français. Un titre absent de cette liste s'affiche en français.
Utilisation : python3 scripts/titres-traduits.py  ->  scripts/titres-traduits.json"""
import json
T = {
"rencontre-du-shaykh-avec-un-chef-de-tribu-indigene-au-bresil": ("The Shaykh meets an indigenous tribal chief in Brazil", "لقاء الشيخ مع زعيم قبيلة من السكان الأصليين في البرازيل"),
"le-shaykh-mohamed-faouzi-al-karkari-invite-de-linstitut-de-parapsychologie-de-jo": ("Shaykh Mohamed Faouzi al-Karkari, guest of the Parapsychology Institute of Joinville (Brazil)", "الشيخ محمد فوزي الكركري ضيفًا على معهد علم النفس الخارق في جوانفيلي (البرازيل)"),
"le-shaykh-mohamed-faouzi-al-karkari-invite-de-luniversite-regionale-de-blumenau-": ("Shaykh Mohamed Faouzi al-Karkari, guest of the Regional University of Blumenau, Brazil", "الشيخ محمد فوزي الكركري ضيفًا على جامعة بلومينو الإقليمية في البرازيل"),
"cloture-de-la-visite-du-shaykh-mohamed-faouzi-al-karkari-a-geneve": ("Closing of Shaykh Mohamed Faouzi al-Karkari's visit to Geneva", "ختام زيارة الشيخ محمد فوزي الكركري إلى جنيف"),
"shaykh-mohamed-faouzi-al-karkari-invite-a-une-voix-pour-la-paix": ("Shaykh Mohamed Faouzi al-Karkari invited to “A Voice for Peace”", "الشيخ محمد فوزي الكركري مدعوًّا إلى «صوتٌ من أجل السلام»"),
"la-saintete-a-la-lumiere-du-soufisme-et-de-la-recherche-academique-conference-du": ("Sainthood in the light of Sufism and academic research: Shaykh Mohamed Faouzi al-Karkari's lecture at Yale University", "الولاية في ضوء التصوف والبحث الأكاديمي: محاضرة الشيخ محمد فوزي الكركري في جامعة ييل"),
"le-shaykh-mohamed-faouzi-al-karkari-invite-a-luniversite-de-yale": ("Shaykh Mohamed Faouzi al-Karkari invited to Yale University", "الشيخ محمد فوزي الكركري مدعوًّا إلى جامعة ييل"),
"invitation-de-linstitut-al-karkari-a-la-bibliotheque-houghton-de-harvard": ("The Al-Karkari Institute invited to Harvard's Houghton Library", "دعوة معهد الكركري إلى مكتبة هوتون في هارفارد"),
"le-shaykh-mohamed-faouzi-al-karkari-linvite-a-luniversite-de-bloomington-indiana": ("Shaykh Mohamed Faouzi al-Karkari, guest at Bloomington University (Indiana, USA)", "الشيخ محمد فوزي الكركري ضيفًا على جامعة بلومنغتون (إنديانا، الولايات المتحدة)"),
"le-shaykh-mohamed-faouzi-al-karkari-a-la-zawiya-karkariya-de-lyon-condrieu-21-12": ("Shaykh Mohamed Faouzi al-Karkari at the Karkariya zawiya of Lyon-Condrieu (21-12-24)", "الشيخ محمد فوزي الكركري في الزاوية الكركرية بليون-كوندريو (21-12-2024)"),
"le-shaykh-mohamed-faouzi-al-karkari-au-forum104-19-12-24": ("Shaykh Mohamed Faouzi al-Karkari at Forum104 (19/12/24)", "الشيخ محمد فوزي الكركري في منتدى 104 (19/12/2024)"),
"linstitut-al-karkari-a-luniversite-de-stanford-et-berkeley": ("The Al-Karkari Institute at Stanford and Berkeley universities", "معهد الكركري في جامعتي ستانفورد وبيركلي"),
"mawlid-2023-photos-videos": ("Mawlid 2023 — Photos & videos", "المولد النبوي 2023 — صور وفيديوهات"),
"lassociation-moche-benmimoun-pour-le-patrimoine-juif-au-maroc-et-le-vivre-ensemb": ("The “Moche Benmimoun Association for Jewish Heritage in Morocco and Living Together” visits the Karkariya Zawiya", "جمعية «موشي بنميمون للتراث اليهودي بالمغرب والعيش المشترك» تزور الزاوية الكركرية"),
"les-sept-engagements": ("The seven commitments", "الالتزامات السبعة"),
"lislam-soufi-de-la-karkariya-dans-le-cursus-des-plus-grandes-universites-america": ("The Sufi Islam of the Karkariya in the curricula of the leading American universities", "التصوف الإسلامي للكركرية في مناهج كبريات الجامعات الأمريكية"),
"80-kits-scolaires-pour-les-orphelins-de-bagalbari-inde": ("80 school kits for the orphans of Bagalbari (India)", "80 حقيبة مدرسية ليتامى باغالباري (الهند)"),
"la-celebration-du-mawlid-par-la-karkariya-dans-les-journaux-du-monde-entier": ("The Karkariya's celebration of the Mawlid in newspapers around the world", "احتفال الكركرية بالمولد النبوي في صحف العالم"),
"construction-dun-puits-a-machingwom-cameroun": ("Building a well in Machingwom (Cameroon)", "بناء بئر في ماشينغوم (الكاميرون)"),
"don-dun-tricycle-synonyme-de-liberte-et-autonomie": ("Donation of a tricycle, a symbol of freedom and independence", "التبرع بدراجة ثلاثية العجلات، رمز الحرية والاستقلال"),
"la-karkariya-construit-une-ecole-primaire-au-ghana": ("The Karkariya builds a primary school in Ghana", "الكركرية تبني مدرسة ابتدائية في غانا"),
"la-karkariya-fait-don-dune-camionnette-a-lorphelinat-fanantenana-madagascar": ("The Karkariya donates a van to the Fanantenana orphanage (Madagascar)", "الكركرية تتبرع بشاحنة صغيرة لدار الأيتام فانانتينانا (مدغشقر)"),
"de-leau-potable-pour-les-rohingyas": ("Drinking water for the Rohingya", "مياه صالحة للشرب للروهينغا"),
"la-karkariya-construit-un-puits-a-madaripur-bangladesh": ("The Karkariya builds a well in Madaripur (Bangladesh)", "الكركرية تبني بئرًا في مداريبور (بنغلاديش)"),
"action-humanitaire-de-la-karkariya-a-gamboru-nigeria": ("Humanitarian action by the Karkariya in Gamboru (Nigeria)", "عمل إنساني للكركرية في غامبورو (نيجيريا)"),
"construction-dun-puits-a-islampur-bangladesh": ("Building a well in Islampur (Bangladesh)", "بناء بئر في إسلام بور (بنغلاديش)"),
"le-shaykh-mohamed-faouzi-al-karkari-en-soutien-au-sahara-marocain": ("Shaykh Mohamed Faouzi Al Karkari in support of the Moroccan Sahara", "الشيخ محمد فوزي الكركري يدعم الصحراء المغربية"),
"la-fondation-trophee-de-lafricanite-decerne-le-trophee-de-lafricanite-au-cheikh-": ("The Africanity Trophy Foundation awards the Africanity Trophy to Sheikh Mohamed Fawzi Al Karkari", "مؤسسة كأس الأفريقانية تمنح كأس الأفريقانية للشيخ محمد فوزي الكركري"),
"sous-les-auspices-des-nations-unies-fondation-trophee-de-lafricanite-attribue-le": ("Under the auspices of the United Nations, the Africanity Trophy Foundation awards a certificate of honour to Sidi Shaykh Mohamed Faouzi Al Karkari", "تحت رعاية الأمم المتحدة، مؤسسة كأس الأفريقانية تمنح شهادة تكريم لسيدي الشيخ محمد فوزي الكركري"),
"les-karkaris-du-niger-entreprennent-une-action-humanitaire-a-kabawa": ("The Karkaris of Niger undertake a humanitarian action in Kabawa", "الكركريون في النيجر يقومون بعمل إنساني في كاباوا"),
"les-disciples-karkaris-togolais-organisent-un-repas-festif-pour-200-orphelins": ("Togolese Karkari disciples organise a festive meal for 200 orphans", "مريدو الكركرية في توغو ينظمون وليمة لمئتي يتيم"),
"les-disciples-karkaris-ghaneens-font-la-joie-des-orphelins-du-village-dave": ("Ghanaian Karkari disciples bring joy to the orphans of Dave village", "مريدو الكركرية في غانا يُدخلون الفرحة على أيتام قرية دافي"),
"les-disciples-karkaris-apportent-de-la-joie-aux-habitants-de-thana-ghora": ("Karkari disciples bring joy to the inhabitants of Thana Ghora", "مريدو الكركرية يُدخلون الفرحة على سكان ثانا غورا"),
"les-karkaris-ivoiriens-creusent-un-puits-deau-potable-a-tehiri": ("Ivorian Karkaris dig a drinking-water well in Tehiri", "الكركريون في كوت ديفوار يحفرون بئر ماء صالح للشرب في تيهيري"),
"la-karkaris-malgaches-construisent-un-puits-a-tsianaloka": ("Malagasy Karkaris build a well in Tsianaloka", "الكركريون في مدغشقر يبنون بئرًا في تسيانالوكا"),
"les-krkaris-belges-mettent-du-baume-au-coeur-des-sans-papiers-africains": ("Belgian Karkaris comfort undocumented African migrants", "الكركريون في بلجيكا يواسون المهاجرين الأفارقة غير النظاميين"),
"les-disciples-karkaris-de-linde-menent-une-action-humanitaire-a-ajmer-rajasthan": ("Karkari disciples of India carry out a humanitarian action in Ajmer (Rajasthan)", "مريدو الكركرية في الهند يقومون بعمل إنساني في أجمير (راجستان)"),
"la-zawya-karkariya-malgache-en-fete": ("The Malagasy Karkariya zawiya celebrates", "الزاوية الكركرية في مدغشقر تحتفل"),
"les-karkaris-apportent-de-laide-aux-musulmans-rohingyas": ("The Karkaris bring aid to Rohingya Muslims", "الكركريون يقدمون العون للمسلمين الروهينغا"),
"les-karkaris-ivoiriens-secourent-les-sinistres-danyama": ("Ivorian Karkaris come to the aid of the flood victims of Anyama", "الكركريون في كوت ديفوار يغيثون منكوبي أنياما"),
"les-villageois-philippins-remercient-la-karkariya": ("Filipino villagers thank the Karkariya", "قرويون في الفلبين يشكرون الكركرية"),
"les-disciples-karkaris-togolais-en-lutte-contre-la-cataracte": ("Togolese Karkari disciples fight cataracts", "مريدو الكركرية في توغو يكافحون الساد (الكاتاراكت)"),
"deuxieme-action-humanitaire-de-la-karkariya-aux-philippines": ("Second humanitarian action by the Karkariya in the Philippines", "العمل الإنساني الثاني للكركرية في الفلبين"),
"deuxieme-action-humanitaire-au-bresil": ("Second humanitarian action in Brazil", "العمل الإنساني الثاني في البرازيل"),
"action-humanitaire-de-la-karkariya-au-bresil": ("Humanitarian action by the Karkariya in Brazil", "عمل إنساني للكركرية في البرازيل"),
"action-humanitaire-de-la-karkariya-a-udaipur-city-inde": ("Humanitarian action by the Karkariya in Udaipur City (India)", "عمل إنساني للكركرية في مدينة أودايبور (الهند)"),
"action-humanitaire-de-la-karkariya-au-ghana": ("Humanitarian action by the Karkariya in Ghana", "عمل إنساني للكركرية في غانا"),
"initiative-humanitaire-de-la-karkariya-au-nepal": ("Humanitarian initiative by the Karkariya in Nepal", "مبادرة إنسانية للكركرية في نيبال"),
"la-karkariya-apporte-de-la-joie-aux-habitants-de-deux-villages-senegalais": ("The Karkariya brings joy to the inhabitants of two Senegalese villages", "الكركرية تُدخل الفرحة على سكان قريتين سنغاليتين"),
"la-tariqa-karkariya-entreprend-une-initiative-humanitaire-aux-philippines": ("The Karkariya Sufi Order undertakes a humanitarian initiative in the Philippines", "الطريقة الكركرية تطلق مبادرة إنسانية في الفلبين"),
"lapport-des-soufis-a-la-societe-lexemple-de-la-voie-karkariya": ("The contribution of Sufis to society: the example of the Karkariya Path", "إسهام الصوفية في المجتمع: نموذج الطريقة الكركرية"),
"photos-videos-visite-du-shaykh-a-bordeaux-01-2020": ("Photos & videos – The Shaykh's visit to Bordeaux (01/2020)", "صور وفيديوهات – زيارة الشيخ إلى بوردو (01/2020)"),
"photos-videos-visite-du-shaykh-a-montauban-01-2020": ("Photos & videos – The Shaykh's visit to Montauban (01/2020)", "صور وفيديوهات – زيارة الشيخ إلى مونتوبان (01/2020)"),
"photos-videos-visite-du-shaykh-a-lyon-12-2019": ("Photos & videos – The Shaykh's visit to Lyon (12/2019)", "صور وفيديوهات – زيارة الشيخ إلى ليون (12/2019)"),
"visite-du-shaykh-a-paris-12-2019-photos-videos": ("The Shaykh's visit to Paris (12/2019) – Photos & videos", "زيارة الشيخ إلى باريس (12/2019) – صور وفيديوهات"),
"visite-du-shaykh-a-lille-12-2019-photos-videos": ("The Shaykh's visit to Lille (12/2019) – Photos & videos", "زيارة الشيخ إلى ليل (12/2019) – صور وفيديوهات"),
"photos-videos-mawlid-2019": ("Photos & videos – Mawlid 2019", "صور وفيديوهات – المولد النبوي 2019"),
"la-foire-musulmane-ramf-2019": ("The Muslim fair (RAMF) 2019", "المعرض الإسلامي (RAMF) 2019"),
"sidi-shaykh-a-paris-mars-2019": ("Sidi Shaykh in Paris (March 2019)", "سيدي الشيخ في باريس (مارس 2019)"),
"rencontre-en-lumiere-mars-2019": ("Meeting in Light (March 2019)", "لقاء في النور (مارس 2019)"),
"visite-du-shaykh-a-venise-2019": ("The Shaykh's visit to Venice (2019)", "زيارة الشيخ إلى البندقية (2019)"),
"visite-du-shaykh-a-lyon-2019": ("The Shaykh's visit to Lyon (February 2019)", "زيارة الشيخ إلى ليون (فبراير 2019)"),
"mawlid-en-lumiere-2018-photos-videos": ("Mawlid in Light (2018) – Photos & videos", "المولد في النور (2018) – صور وفيديوهات"),
"mawlid-2018-photos-videos": ("Mawlid 2018 – Photos & videos", "المولد النبوي 2018 – صور وفيديوهات"),
"mawlid-2017-photos-videos": ("Mawlid 2017 – Photos & videos", "المولد النبوي 2017 – صور وفيديوهات"),
"1000-km-de-marche-jusqua-mon-shaykh": ("1,000 km on foot to my Shaykh", "ألف كيلومتر مشيًا على الأقدام إلى شيخي"),
"rencontre-toute-fraterni-the-4eme-edition-1017": ("Meeting in all “fraterni-tea” – 4th edition (10/17)", "لقاء «أخوّة وشاي» – النسخة الرابعة (10/2017)"),
"veillee-spirituelle-shaykh-a-paris-rencontre-toute-fraterni-the": ("Spiritual evening with the Shaykh in Paris", "أمسية روحية مع الشيخ في باريس"),
"celebration-de-mariage-paris-02042017": ("Wedding celebration – Paris (02/04/2017)", "حفل زفاف – باريس (02/04/2017)"),
"encouragement-conseil-shaykh-paris-02042017": ("The Shaykh's encouragement and advice – Paris (02/04/2017)", "تشجيع ونصيحة الشيخ – باريس (02/04/2017)"),
"rencontre-toute-fraterni-the-visite-shaykh-paris-01042017": ("Meeting in all “fraterni-tea” & the Shaykh's visit – Paris (01/04/2017)", "لقاء «أخوّة وشاي» وزيارة الشيخ – باريس (01/04/2017)"),
"visite-shaykh-europe-dreux-31032017": ("The Shaykh's visit to Europe – Dreux (31/03/2017)", "زيارة الشيخ إلى أوروبا – درو (31/03/2017)"),
"visite-shaykh-europe-lille-30032017": ("The Shaykh's visit to Europe – Lille (30/03/2017)", "زيارة الشيخ إلى أوروبا – ليل (30/03/2017)"),
"mawlid-2016-fete-de-lhumanite": ("Mawlid 2016 – Festival of Humanity", "المولد النبوي 2016 – عيد الإنسانية"),
"vision-trois-siyaha-basmala": ("One vision. Three siyaha. One basmala.", "رؤيا واحدة. ثلاث سياحات. بسملة واحدة."),
"siyaha-lille-avignon-9-conversions-2": ("Siyaha Lille–Avignon & 9 conversions", "سياحة من ليل إلى أفينيون و9 حالات اعتناق للإسلام"),
"salon-bourget-2016-ramf": ("The Le Bourget show 2016 (RAMF)", "معرض لوبورجيه 2016 (RAMF)"),
"visite-du-lieu-de-naissance-de-sidi-shaykh": ("Visit to Sidi Shaykh's birthplace", "زيارة مسقط رأس سيدي الشيخ"),
"visite-guidee-de-la-nouvelle-zawiya-mere": ("Guided tour of the new mother zawiya", "جولة في الزاوية الأم الجديدة"),
"visite-du-darih-de-lala-sati-a-tlemcen": ("Visit to the shrine of Lalla Sati in Tlemcen", "زيارة ضريح لالة ستي في تلمسان"),
"la-karkariya-au-colloque-aisa-a-lunesco": ("The Karkariya at the AISA Colloquium at UNESCO", "الكركرية في ندوة AISA بمقر اليونسكو"),
"aid-el-adha-2015-a-la-zawiya-karkariya": ("Eid al-Adha 2015 at the Karkariya zawiya", "عيد الأضحى 2015 في الزاوية الكركرية"),
"conference-le-pardon-des-7-saints": ("Lecture “The forgiveness of the 7 Saints”", "محاضرة «مغفرة الأولياء السبعة»"),
"la-karkariya-assiste-a-la-conference-deric-geoffroy": ("The Karkariya attends Eric Geoffroy's lecture", "الكركرية تحضر محاضرة إيريك جوفروا"),
"la-tariqa-karkariya-a-la-conference-de-shaykh-anass-tigra": ("The Karkariya Sufi Order at Shaykh Anass Tigra's lecture", "الطريقة الكركرية في محاضرة الشيخ أنس تيغرا"),
"tente-karkariy-a-bergem-maroc": ("Karkariy tent at Bergem (Morocco)", "الخيمة الكركرية في برغم (المغرب)"),
"zawiya-de-moulay-mohamed-ibn-kaddour-al-wakiliy-al-karkariy": ("The Zawiya of Moulay Mohamed Ibn Kaddour Al Wakiliy Al Karkariy", "زاوية مولاي محمد بن قدور الوكيلي الكركري"),
"visite-de-mawlay-abdessalam-ibn-machich-2": ("Visit to Mawlay Abdessalam ibn Machich", "زيارة مولاي عبد السلام بن مشيش"),
"visite-de-moulay-ahmed-ibn-ajiba-2": ("Visit to Moulay Ahmed ibn ʿAjiba", "زيارة مولاي أحمد بن عجيبة"),
"un-mourid-karkariy-venu-daustralie": ("A Karkariy disciple who came from Australia…", "مريد كركري قدم من أستراليا…"),
"presence-karkariy-au-bourget-2014": ("Karkariy presence at Le Bourget 2014", "حضور كركري في لوبورجيه 2014"),
"visite-karkariya-mosquee-de-paris-mosquee-des-ulis-28032014": ("Karkariya visit: Paris Mosque / Les Ulis Mosque (28/03/2014)", "زيارة كركرية: مسجد باريس / مسجد لي أوليس (28/03/2014)"),
"video-conversion-et-entree-dans-la-tariqa-karkariya-de-notre-soeur-mariam": ("Conversion and entry into the Karkariya Sufi Order of our sister Mariam", "اعتناق أختنا مريم للإسلام ودخولها الطريقة الكركرية"),
"video-conversion-dun-francais-a-la-zawiya-karkariya": ("Conversion of a Frenchman at the Karkariya Zawiya", "اعتناق شاب فرنسي للإسلام في الزاوية الكركرية"),
"conversion-a-lislam-dans-la-zawiya-karkariya-de-al-aroui": ("Conversion to Islam at the Karkariya Zawiya of al-Aroui", "اعتناق الإسلام في الزاوية الكركرية بالعروي"),
# enseignements
"demandez-aux-gens-dhikr-ne-savez": ("Ask the people of dhikr, if you do not know", "اسألوا أهل الذكر إن كنتم لا تعلمون"),
"le-savoir": ("Knowledge", "العلم"),
"vision-yeux-vision-coeur": ("The vision of the eyes and the Vision of the Heart", "رؤية العين ورؤية القلب"),
"tafsir-al-hujurat-appartements": ("Tafsir of Sūrat al-Ḥujurāt (the Chambers)", "تفسير سورة الحجرات"),
"le-coeur-spirituel-dans-le-coeur-physique": ("The spiritual heart within the physical heart", "القلب الروحي في القلب الجسدي"),
"assise-du-shaykh-lordre-des-versets": ("The Shaykh's gathering: the order of the verses", "مجلس الشيخ: ترتيب الآيات"),
"la-feconnaissance-pour-les-bienfaits-dallah-30102015": ("Gratitude for Allah's blessings", "الشكر على نعم الله"),
"5570-2": ("“We only became Shaykhs by having read two books”", "«ما صرنا شيوخًا إلا بقراءة كتابين»"),
"cours-30052014-connaitre-allah-par-sa-beaute-sublime": ("(Lesson) Knowing Allah through His Sublime Beauty", "(درس) معرفة الله بجماله السامي"),
"cours-14032014-le-secret-de-la-baya": ("(Lesson) The Secret of the Bay'a", "(درس) سرّ البيعة"),
"hadith-al-nouzoul-asrar-de-lism-le-sheykh-wassita-la-prohibitif": ("(Lesson) The Hadith of Descent, the secrets of the Name, the Shaykh (Wassita), the prohibitive lā", "(درس) حديث النزول، أسرار الاسم، الشيخ (الواسطة)، لا الناهية"),
"cours-150214-themes-ism-existantinexistant-la-prohibitif-sens-caches-de-alif-lam": ("(Lesson) The Name, existent/non-existent, the prohibitive lā, hidden meanings of “Alif Lām Mīm”", "(درس) الاسم، الموجود والمعدوم، لا الناهية، المعاني الخفية لـ «الم»"),
"cours-281213-themes-safar-12-24-66-idhn": ("(Lesson) Safar, 12-24-66, idhn", "(درس) السفر، 12-24-66، الإذن"),
}
json.dump(T, open("scripts/titres-traduits.json", "w"), ensure_ascii=False, indent=1)
print(len(T), "titres")
